### ISSUE TITLE
website: add header anchor links on hover

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1028]
Many sites have a pattern where if you hover on the H1, H2, H3 etc elements, their `id="foo"` attribute shows up as a link to `<a href="#foo">`.

I'd like that for the Perkeep website.

e.g. https://github.com/ipfs/ipfs#quick-summary (hover over `Quick Summary`) and see the:

<img width="193" alt="screen shot 2018-01-09 at 8 14 44 am" src="https://user-images.githubusercontent.com/2621/34730761-2ed38e1c-f515-11e7-9e93-c034432b41af.png">

... on the left of the text.

/cc @willnorris

**Comment by peteretelej** [comment]
Enabling this functionality with JavaScript would be by appending an appropriate link (svg) to all headers with ids, and styling appropriately. 

I could work on this if that'd suffice, it'll will achieve desired functionality with little code change.

**Comment by willnorris** [comment]
That would be great, thanks @peteretelej!

**Comment by peteretelej** [comment]
Sent a change https://camlistore-review.googlesource.com/c/camlistore/+/14386

One thing I wasn't sure about: added the js at the end of `tmpl/page.html`. Not sure if you'd want that in a separate js file. Since it'll be required for all pages, I think inlining may be better that the additional http req.

Also found some few minor html/css issues:
- missing doctype declaration at start of `page.html`
```css
a.local {                                                                  
    text-underline: dotted-underline;  /* TODO: i forget. look this up */  
}                                                                          
```
- maybe `text-decoration: underline dashed` or `underline dotted`
```html
```
- `<script type="text/javascript" src="/static/all-async.js" async="true">`
can just be `<script src="/static/all-async.js" async>`, ie not `type`
- a few other small html issues like these.

I could help clean up these up, should I open an issue?
