### ISSUE TITLE
Simplify config file formats (and move to toml)

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1134]
There are several things I don't like about our current client & server configs (mostly our server configs):

* it's JSON, so you can't have comments
* it's JSON, so you have to worry about when commas are valid
* that we have the "high-level" (easy) server config and the "low-level" (powerful, but impossible to read) server config file format, and we have to document both (which is confusing), and sometimes something's not possible with the high-level config and you're suddenly forced to mass-convert your config to the hard (and unreadable) JSON format, and all the JSON and boilerplate in the resulting mess makes it hard to see what your config is actually trying to say.

Both have been bugging me for awhile, and then I finally read the spec for the https://github.com/toml-lang/toml format and I kinda love it.

After discussion and design with @mpl and @edrex at LFNW'18, the new plan is to move to toml and only have one config format that's easy to read and easy to document and easier to incrementally tweak for users.

We're thinking something like:

```toml
[network]
baseURL = "https://pk.perkeep.org"
listen = ":4430"
https = true
auth = ["localhost", "userpass:bradfitz:foo"]

[vars]
DATA = "${ENV:HOME}/var/perkeep"

[identity]
id = "f3dcaa1234"
ring = "${ENV:HOME}/.config/perkeep/identity-secring.gpg"

[server]
share_handler  = true  # true by default, but explicit                                                                                                    
ui_handler     = true  # true by default too                                                                                                              
search_handler = false # true by default                                                                                                                  

# where incoming blob writes go. by default they go to the first listed storage?                                                                          
# but this can be an array of multiple, in which case there's an implicit "replica" type                                                                  
# created to do synchronous writes.                                                                                                                       
blob_writes = ["blobpacked"]

[index]
type = "leveldb"
dir = "$DATA/camli-index.leveldb"
from = "blobpacked"

[[storage]]
type = "blobpacked"
loose = { type = "localdisk", dir = "$DATA" }
packed = { type = "localdisk", dir = "$DATA/packed" }
meta = { type = "leveldb", dir = "$DATA/packed/packindex.leveldb" }

[[storage]]
type = "s3"
bucket = "bradfitz-perkeep-bucket"
clientID = "yyyy"
secret = "xxxx"

[[storage]]
type = "googlecloudstorage"
bucket = "bradfitz-perkeep-bucket"
clientID = "yyyy2"
secret = "xxxx2"

[[sync]]
from = "blobpacked"
to = "s3"
verifyInterval = "30d"

[[sync]]
from = "blobpacked"
to = "googlecloudstorage"
verifyInterval = "30d"

[[sync]]
from = "blobpacked"
to = "index"
verifyInterface = "1d"
```

Notes:

* you can define multiple storage sections (hence the `[[...]]`` syntax to let you define an array of objects)
* each storage must have a `type`, which is the implementation of the blobserver interface in the code. Same as today. This is required. That implementation then validates the rest of the config, also like today.
* each storage can have a unique and URL-friendly name (no slashes, whitespace), but if no name is specified, it gets a default name of its `type`, so I didn't need to name `"s3"` in the example above. The name is used to refer to it.
* some storages can be defined inline (as in the blobpacked example above with loose & packed blobs), in which case they're not named, but they don't need to be referred to directly. If you want a URL for them (to address them directly), they'll need to be pulled out into their own section with a name and then the value of the "loose" parameter can be a string (a storage name) instead of an object (a storage definition).
* you can define multiple `[[sync]]` pairs, which you can't do today in the high-level config.
* you can specify where blobs writes go to, but by default we pick the first one.
* we'll probably add some implicit cache/cond/replica storage types for you to wire things up if you don't specify a connected graph explicitly.
* we'll let you define a common variables in a vars section, and let you reach out into environment variables too, but make the latter uglier.
* but we don't want too much implicit magic. Since we auto-generate these on start, we're not aiming to have them be super minimal, but we want them to be readable. We think it's more readable to have a few auto-generated lines that are explicit rather than a ton of implicit magic you need to look up later.
